#
# Copyright 2025 Kealu Inc. All rights reserved.
# Licensed under the Kealu Vector License v1.0 — PATENT PENDING
#

"""Committed box measurements, and the guarantee they match their document.

:mod:`benefits_navigator.formmap.measure` derives boxes from what a document
prints. Doing that needs ``pdftotext`` and a few seconds per document, neither
of which belongs on a render path, so the derivation runs once — offline, in
``tools/measure_texas_forms.py`` — and its output is committed here as JSON.

That makes the measurements reviewable: a diff shows exactly which boxes moved
when someone adjusts an anchor, in points, next to the anchor that produced
them. It is the difference between reviewing "we changed the gap from 1.5 to
2.0" and reviewing eighty changed floats with no way to tell which are right.

── The staleness guarantee ────────────────────────────────────────────────
A measurement file records the SHA-256 of the document it was taken from, and
:func:`load_measurements` refuses to return boxes whose digest does not match
the document about to be drawn on. Combined with the same check in
:mod:`benefits_navigator.formmap.provenance`, this closes the loop the brief
asks for: **updating a PDF cannot silently retain stale coordinates.** Dropping
a new HHSC revision into ``forms/`` produces an error naming the file, not a
form with an applicant's income printed over a printed label.

Regenerating is deliberately a separate, explicit step. There is no "measure if
missing" fallback, because that would turn a stale-document error into a silent
re-measurement against a document nobody has looked at.
"""

from __future__ import annotations

import json
from pathlib import Path

from benefits_navigator.formmap.provenance import OfficialDocument
from benefits_navigator.formmap.targets import Box

#: Where measurement files live, beside the form definitions that read them.
MEASUREMENTS_DIR = Path(__file__).resolve().parent / "forms" / "measurements"


class MeasurementsOutOfDate(RuntimeError):
    """A measurement file was taken from a different document than the one held."""


class MeasurementsMissing(RuntimeError):
    """A form declares measurements that have never been generated."""


def measurements_path(document: OfficialDocument) -> Path:
    """Where `document`'s measurements are committed."""
    return MEASUREMENTS_DIR / f"{Path(document.filename).stem}.json"


def load_measurements(document: OfficialDocument) -> dict[str, tuple[Box, ...]]:
    """Every measured box for `document`, keyed by canonical key.

    A key maps to a *tuple* of boxes even when there is only one, because a
    date split across printed month/day/year cells is as ordinary here as a
    single line, and a caller that has to check the type first will eventually
    forget to.
    """
    path = measurements_path(document)

    try:
        raw = json.loads(path.read_text())
    except FileNotFoundError:
        raise MeasurementsMissing(
            f"{document.filename} has no committed measurements at {path}. "
            f"Generate them with:\n"
            f"    .venv/bin/python tools/measure_texas_forms.py\n"
            f"and read the diff before committing."
        ) from None

    recorded = raw.get("document_sha256", "")

    if recorded != document.sha256:
        raise MeasurementsOutOfDate(
            f"{path.name} was measured against a different document.\n"
            f"  measurements taken from sha256 {recorded}\n"
            f"  document now declared as     {document.sha256}\n"
            f"The boxes below are positions on the old layout and would print "
            f"in the wrong places. Re-run tools/measure_texas_forms.py, then "
            f"render every scenario and look at the pages before trusting the "
            f"result."
        )

    boxes: dict[str, tuple[Box, ...]] = {}

    for key, entries in raw.get("boxes", {}).items():
        boxes[key] = tuple(
            Box(page=int(e[0]), x=e[1], y=e[2], width=e[3], height=e[4])
            for e in entries
        )

    return boxes


def write_measurements(
    document: OfficialDocument, boxes: dict[str, tuple[Box, ...]]
) -> Path:
    """Commit `boxes` as `document`'s measurements. Used only by the tool."""
    path = measurements_path(document)
    path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "document": document.filename,
        "document_sha256": document.sha256,
        "printed_revision": document.printed_revision,
        "languages": list(document.languages),
        "_comment": (
            "Generated by tools/measure_texas_forms.py from the anchors in the "
            "form definition. Do not hand-edit: change the anchor and "
            "regenerate, so the box and the printed text it was derived from "
            "cannot disagree. Boxes are [page, x, y, width, height] in PDF "
            "user space, origin bottom-left."
        ),
        "boxes": {
            key: [[b.page, _r(b.x), _r(b.y), _r(b.width), _r(b.height)] for b in group]
            for key, group in sorted(boxes.items())
        },
    }

    path.write_text(json.dumps(payload, indent=2) + "\n")

    return path


def _r(value: float) -> float:
    """Rounded to a tenth of a point — finer than any printer resolves."""
    return round(value, 1)
